name: NotesApp
options:
  bundleIdPrefix: com.agency
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    TARGETED_DEVICE_FAMILY: "1,2"

targets:
  NotesApp:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: Sources
        type: group
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.agency.notesapp
        INFOPLIST_VALUES:
          CFBundleDisplayName: NotesApp
          UILaunchScreen: {}
